#!/usr/bin/env bun
/**
 * Generates `dist-embed.generated.ts`: one `with { type: "file" }` import per
 * built collab-web asset, plus a path -> file map.
 *
 * Import attributes embed files on every Bun version and behave identically in
 * `bun relay.ts` (real path) and in a compiled binary (embedded blob), unlike
 * `bun build --asset <dir>`, which Bun 1.3.13 does not have. Exact-match
 * routing also removes any path-traversal surface from static serving.
 *
 * No `dist/` (nobody ran `bun run client`) generates an empty map: the relay
 * still works, it just serves no browser client.
 */
import { existsSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = join(import.meta.dir, "..");
const DIST = join(ROOT, "dist");
const OUT = join(ROOT, "dist-embed.generated.ts");

function walk(dir: string): string[] {
	return readdirSync(dir).flatMap((name) => {
		const full = join(dir, name);
		return statSync(full).isDirectory() ? walk(full) : [full];
	});
}

const files = existsSync(DIST) ? walk(DIST).sort() : [];
const imports: string[] = [];
const entries: string[] = [];

files.forEach((file, i) => {
	imports.push(`import f${i} from "./${relative(ROOT, file)}" with { type: "file" };`);
	entries.push(`\t"/${relative(DIST, file)}": f${i},`);
});

writeFileSync(
	OUT,
	[
		"// Generated by scripts/embed-dist.ts. Do not edit.",
		'// @ts-nocheck — `with { type: "file" }` on assets is a Bun loader, unknown to tsc.',
		"// biome-ignore-all lint: generated",
		"",
		...imports,
		imports.length > 0 ? "" : null,
		"/** Request path -> embedded file path. Unlisted paths fall back to index.html. */",
		"export const EMBEDDED_FILES: Record<string, string> = {",
		...entries,
		"};",
		"",
	]
		.filter((line) => line !== null)
		.join("\n"),
);

console.log(
	files.length > 0 ? `embedded ${files.length} files from dist/` : "no dist/ — building without a web client",
);
